200_VENDORS/002_REFINED/1005_SP

diff --git a/.github/workflows/demo_vendors.yml b/.github/workflows/demo_vendors.yml
--- a/.github/workflows/demo_vendors.yml
+++ b/.github/workflows/demo_vendors.yml
@@ -5,7 +5,7 @@ on:
     branches:
       - main
     paths:
-      - '200_VENDORS/**'
+      - '200_VENDORS/002_REFINED/**'
 
 jobs:
   deploy-snowflake-changes-job:
@@ -43,7 +43,7 @@ jobs:
         run: |
           echo "Deploying to environment: ${ENV}"
           python --version
-          schemachange -f $GITHUB_WORKSPACE/200_VENDORS -a $SF_ACCOUNT -u $SNOWFLAKE_USER -r $SF_ROLE -w $SF_WAREHOUSE --vars '{"env": "'${ENV}'"}' -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table || echo "Schema change failed"
+          schemachange -f $GITHUB_WORKSPACE/200_VENDORS/002_REFINED -a $SF_ACCOUNT -u $SNOWFLAKE_USER -r $SF_ROLE -w $SF_WAREHOUSE --vars '{"env": "'${ENV}'"}' -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table || echo "Schema change failed"
 
       - name: Call ingestion procedure
         if: ${{ contains(github.event.head_commit.message, '200_VENDORS/002_REFINED/1005_SP') }}
