8-10-1

diff --git a/.github/workflows/demo_vendors.yml b/.github/workflows/demo_vendors.yml
--- a/.github/workflows/demo_vendors.yml
+++ b/.github/workflows/demo_vendors.yml
@@ -11,25 +11,25 @@ jobs:
   deploy-snowflake-changes-job:
     runs-on: ubuntu-latest
 
-    # Specify that the job will run for the selected environment based on the ENV repository secret
     environment: ${{ vars.ENV }}
 
     steps:
       - name: Checkout repository
         uses: actions/checkout@v2
 
-      - name: Use Python 3.8.x
-        uses: actions/setup-python@v2.2.1
+      - name: Set up Python
+        uses: actions/setup-python@v2
         with:
-          python-version: 3.8.x
+          python-version: '3.8'
+
+      - name: Install dependencies
+        run: pip install schemachange
 
       - name: Set environment variable
-        env:
-          ENV: ${{ vars.ENV }}  
         run: echo "ENV=${{ vars.ENV }}" >> $GITHUB_ENV
 
       - name: Run schemachange
-        if: "!contains(github.event.head_commit.message, '200_VENDORS/002_REFINED/1005_SP')"
+        if: ${{ !contains(github.event.head_commit.message, '200_VENDORS/002_REFINED/1005_SP') }}
         env:
           SF_ACCOUNT: ${{ vars.SF_ACCOUNT }}
           SF_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
@@ -40,24 +40,19 @@ jobs:
           ENV: ${{ vars.ENV }}
         run: |
           echo "Deploying to environment: ${ENV}"
-          echo "GITHUB_WORKSPACE: $GITHUB_WORKSPACE"
           python --version
-          echo "Step 1: Installing schemachange"
-          pip install schemachange
-
-          echo "Step 2: Running schemachange"
-          schemachange -f $GITHUB_WORKSPACE/200_VENDORS/002_REFINED -a $SF_ACCOUNT -u $SNOWFLAKE_USER -r $SF_ROLE -w $SF_WAREHOUSE --vars '{"env": "'${ENV}'"}' -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table
+          schemachange -f $GITHUB_WORKSPACE/200_VENDORS/002_REFINED -a $SF_ACCOUNT -u $SNOWFLAKE_USER -r $SF_ROLE -w $SF_WAREHOUSE --vars '{"env": "'${ENV}'"}' -d $SF_DATABASE -c $SF_DATABASE.SCHEMACHANGE.CHANGE_HISTORY --create-change-history-table || echo "Schema change failed"
 
       - name: Call ingestion procedure
-        if: "contains(github.event.head_commit.message, '200_VENDORS/002_REFINED/1005_SP')"
+        if: ${{ contains(github.event.head_commit.message, '200_VENDORS/002_REFINED/1005_SP') }}
         env:
-            SF_ACCOUNT: ${{ vars.SF_ACCOUNT }}
-            SF_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
-            SNOWFLAKE_USER: ${{ vars.SF_USERNAME }}
-            SF_ROLE: ${{ vars.SF_ROLE }}
-            SF_DATABASE: ${{ vars.SF_VENDORS_DATABASE }}
-            SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
-            ENV: ${{ vars.ENV }}
+          SF_ACCOUNT: ${{ vars.SF_ACCOUNT }}
+          SF_WAREHOUSE: ${{ vars.SF_WAREHOUSE }}
+          SNOWFLAKE_USER: ${{ vars.SF_USERNAME }}
+          SF_ROLE: ${{ vars.SF_ROLE }}
+          SF_DATABASE: ${{ vars.SF_VENDORS_DATABASE }}
+          SNOWFLAKE_PASSWORD: ${{ secrets.SF_PASSWORD }}
+          ENV: ${{ vars.ENV }}
         run: |
-            echo "Calling the ingestion procedure: ${ENV}_PEOPLESOFT_RAW_TO_REFINED_INGESTION"
-            snowsql -a $SF_ACCOUNT -u $SNOWFLAKE_USER -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -f $GITHUB_WORKSPACE/200_VENDORS/002_REFINED/1005_SP/R__200_002_1005_00000001_proc_raw_to_refined_ingestion.sql
+          echo "Calling the ingestion procedure: ${ENV}_PEOPLESOFT_RAW_TO_REFINED_INGESTION"
+          snowsql -a $SF_ACCOUNT -u $SNOWFLAKE_USER -r $SF_ROLE -w $SF_WAREHOUSE -d $SF_DATABASE -f $GITHUB_WORKSPACE/200_VENDORS/002_REFINED/1005_SP/R__200_002_1005_00000001_proc_raw_to_refined_ingestion.sql || echo "Ingestion procedure call failed"
